name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.VEGETABLE_SYC2 }}
          USERNAME: ${{ github.Vegetable-SYC }}
      - name: Commit & Push
        run: |
          git config user.name Vegetable-SYC
          git config user.email 1318270340@qq.com
          git add -A .
          git commit -m "generated"
          git push