name: GitHub-Profile-3D-Contrib

on:
  schedule: 
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.VEGETABLE_SYC2 }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          mv profile-3d-contrib.svg output/profile-3d-contrib.svg

          git config user.name "Vegetable-SYC"
          git config user.email "1318270340@qq.com"
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push || echo "Push failed"
